name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: '14'
        cache: 'npm'

    - run: npm i
    - run: touch arbaz
      working-directory: frontend
    #- run: npm install
    #- run: npm run build
