name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: '14'
        cache: 'npm'
    - name: Clean install dependencies and build  
      run: |
          npm i
          cd frontend
          npm i
          npm run build
          pm2 stop 0
          pm2 start 0
          pm2 save
          sudo service nginx restart
    # - run: npm i
    # - run: npm install
    #   working-directory: frontend
    # - run: npm run build
    #   working-directory: frontend
    # - run:  

      